# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-04 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=150)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('to do', 'to do'), ('Doing', 'Doing'), ('Done', 'Done')], default='to do', max_length=15)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_feature', to=settings.AUTH_USER_MODEL)),
                ('upvotes', models.ManyToManyField(blank=True, related_name='feature_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified_date',),
            },
        ),
    ]
