# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-25 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='context',
            field=models.TextField(max_length=160),
        ),
    ]
