# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-26 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20200526_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='context',
            field=models.TextField(max_length=200),
        ),
    ]
