# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-20 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20200520_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
    ]
