# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-20 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_remove_student_major'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
