# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-30 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='slug',
            field=models.SlugField(max_length=150),
        ),
    ]
