# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-20 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0006_student_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='minor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minor_students', to='bugs.Subject'),
        ),
    ]
