# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-20 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0010_bug_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(choices=[('to do', 'to do'), ('Doing', 'Doing'), ('Done', 'Done')], default='to do', max_length=15),
        ),
    ]
