# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-22 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0012_bug_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='slug',
            field=models.SlugField(default='', max_length=120),
        ),
    ]
