# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-22 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0013_bug_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='slug',
            field=models.SlugField(max_length=120),
        ),
    ]
