# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-23 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0014_auto_20200522_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='bug',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
