# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-24 21:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0015_auto_20200523_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
