# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-25 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0017_auto_20200525_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='bug',
        ),
    ]
